// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvefihcnixucsvdhgmtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2ZWZpaGNuaXh1Y3N2ZGhnbXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjA2MjAsImV4cCI6MjA3MzczNjYyMH0.jXSGY_7DdMeG3z-GU8PDqGE09W-Mo2XeoG6CcnobgtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});